### PR TITLE
BUG FIX: fixing Birthday Song text to reflect actual gameplay

### PR DESCRIPTION
**Pull request by ingernet**
I learned recently (on the Saturday before my birthday, actually) that in New Horizons, KK Slider refuses to perform the Birthday Song until your actual birthday. On the Saturday before, he says something about reserving that song for special occasions. 

You can see this mentioned in Nookipedia, too: https://nookipedia.com/wiki/Secret_song#K.K._Birthday

### CODE REVIEW

**Review by SawyerHood — APPROVED** [review]
Not sure about the translations, but the English looks good!

**Comment by ingernet** [comment]
I ran the phrase through Google Translate for each of the languages, and then clicked the "reverse" button to make sure it translated back accurately. Happy to defer to fluent speakers of those other languages!

**Comment by javmarina** [comment]
Native Spanish speaker here. I would say "en tu cumpleaños" or "el día de tu cumpleaños", both of which are more informal. "En su cumpleaños" is correct nonetheless.

**Comment by ingernet** [comment]
Thank you, Javi! I almost went with “en tu cumpleaños” but then I
remembered my high school Spanish teacher imploring us to use “su” and to
err on the side of formality when in doubt. But! Now that you mention it,
there is almost nothing about ACNH that is formal, unless you count
Blathers. I will put in a PR later today, making this language fix, unless
you beat me to it. :)

**Comment by javmarina** [comment]
I will let you fix it! 😁
We could also wait for other contributors' opinions (@julroy67 is the one that comes to my mind right now).

**Comment by julroy67** [comment]
@javmarina 
Thanks for the notification. I've made a new PR (#34) to fix the translations! :smile:

**Comment by javmarina** [comment]
I also made a new PR (https://github.com/SawyerHood/animal-crossing-catch/pull/35) in order to fix the Spanish string @ingernet .

**Pull request merged**
